// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package solidserver

import (
	"context"
	"reflect"

	"github.com/AthenaWolfe/pulumi-solidserver/sdk/go/solidserver/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// IP PTR data-source allows to easily convert an IPv4 address into a DNS PTR format.
func GetIpPtr(ctx *pulumi.Context, args *GetIpPtrArgs, opts ...pulumi.InvokeOption) (*GetIpPtrResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetIpPtrResult
	err := ctx.Invoke("solidserver:index/getIpPtr:getIpPtr", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIpPtr.
type GetIpPtrArgs struct {
	// The IP address to convert into PTR domain name.
	Address string `pulumi:"address"`
}

// A collection of values returned by getIpPtr.
type GetIpPtrResult struct {
	// The IP address to convert into PTR domain name.
	Address string `pulumi:"address"`
	// The PTR record FQDN associated to the IP address.
	Dname string `pulumi:"dname"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func GetIpPtrOutput(ctx *pulumi.Context, args GetIpPtrOutputArgs, opts ...pulumi.InvokeOption) GetIpPtrResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetIpPtrResult, error) {
			args := v.(GetIpPtrArgs)
			r, err := GetIpPtr(ctx, &args, opts...)
			var s GetIpPtrResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetIpPtrResultOutput)
}

// A collection of arguments for invoking getIpPtr.
type GetIpPtrOutputArgs struct {
	// The IP address to convert into PTR domain name.
	Address pulumi.StringInput `pulumi:"address"`
}

func (GetIpPtrOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIpPtrArgs)(nil)).Elem()
}

// A collection of values returned by getIpPtr.
type GetIpPtrResultOutput struct{ *pulumi.OutputState }

func (GetIpPtrResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIpPtrResult)(nil)).Elem()
}

func (o GetIpPtrResultOutput) ToGetIpPtrResultOutput() GetIpPtrResultOutput {
	return o
}

func (o GetIpPtrResultOutput) ToGetIpPtrResultOutputWithContext(ctx context.Context) GetIpPtrResultOutput {
	return o
}

// The IP address to convert into PTR domain name.
func (o GetIpPtrResultOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v GetIpPtrResult) string { return v.Address }).(pulumi.StringOutput)
}

// The PTR record FQDN associated to the IP address.
func (o GetIpPtrResultOutput) Dname() pulumi.StringOutput {
	return o.ApplyT(func(v GetIpPtrResult) string { return v.Dname }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetIpPtrResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIpPtrResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIpPtrResultOutput{})
}
