// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package solidserver

import (
	"context"
	"reflect"

	"github.com/AthenaWolfe/pulumi-solidserver/sdk/go/solidserver/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// IPv6 subnet query data-source allows to retrieve information about the first IPv6 subnet matching given criterias, including its meta-data.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/AthenaWolfe/pulumi-solidserver/sdk/go/solidserver"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := solidserver.GetIp6SubnetQuery(ctx, &solidserver.GetIp6SubnetQueryArgs{
//				Query: "tag_network_vnid = '12666' AND subnet_allocated_percent < '90.0'",
//				Tags:  pulumi.StringRef("network.vnid"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetIp6SubnetQuery(ctx *pulumi.Context, args *GetIp6SubnetQueryArgs, opts ...pulumi.InvokeOption) (*GetIp6SubnetQueryResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetIp6SubnetQueryResult
	err := ctx.Invoke("solidserver:index/getIp6SubnetQuery:getIp6SubnetQuery", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIp6SubnetQuery.
type GetIp6SubnetQueryArgs struct {
	// The query used to find the first matching subnet.
	Orderby *string `pulumi:"orderby"`
	// The query used to find the first matching subnet.
	Query string `pulumi:"query"`
	// The tags to be used to find the first matching subnet in the query.
	Tags *string `pulumi:"tags"`
}

// A collection of values returned by getIp6SubnetQuery.
type GetIp6SubnetQueryResult struct {
	// The IP subnet address.
	Address string `pulumi:"address"`
	// The class associated to the IPv6 subnet.
	Class string `pulumi:"class"`
	// The class parameters associated to IPv6 subnet.
	ClassParameters map[string]string `pulumi:"classParameters"`
	// The  IPv6 subnet's computed gateway.
	Gateway string `pulumi:"gateway"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The name of the IPv6 subnet.
	Name string `pulumi:"name"`
	// The query used to find the first matching subnet.
	Orderby *string `pulumi:"orderby"`
	// The IPv6 subnet prefix.
	Prefix string `pulumi:"prefix"`
	// The IPv6 subnet's prefix length (ex: 64 for a '/64').
	PrefixSize int `pulumi:"prefixSize"`
	// The query used to find the first matching subnet.
	Query string `pulumi:"query"`
	// The space associated to the IPv6 subnet.
	Space string `pulumi:"space"`
	// The tags to be used to find the first matching subnet in the query.
	Tags *string `pulumi:"tags"`
	// The terminal property of the IPv6 subnet.
	Terminal bool `pulumi:"terminal"`
}

func GetIp6SubnetQueryOutput(ctx *pulumi.Context, args GetIp6SubnetQueryOutputArgs, opts ...pulumi.InvokeOption) GetIp6SubnetQueryResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetIp6SubnetQueryResult, error) {
			args := v.(GetIp6SubnetQueryArgs)
			r, err := GetIp6SubnetQuery(ctx, &args, opts...)
			var s GetIp6SubnetQueryResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetIp6SubnetQueryResultOutput)
}

// A collection of arguments for invoking getIp6SubnetQuery.
type GetIp6SubnetQueryOutputArgs struct {
	// The query used to find the first matching subnet.
	Orderby pulumi.StringPtrInput `pulumi:"orderby"`
	// The query used to find the first matching subnet.
	Query pulumi.StringInput `pulumi:"query"`
	// The tags to be used to find the first matching subnet in the query.
	Tags pulumi.StringPtrInput `pulumi:"tags"`
}

func (GetIp6SubnetQueryOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIp6SubnetQueryArgs)(nil)).Elem()
}

// A collection of values returned by getIp6SubnetQuery.
type GetIp6SubnetQueryResultOutput struct{ *pulumi.OutputState }

func (GetIp6SubnetQueryResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIp6SubnetQueryResult)(nil)).Elem()
}

func (o GetIp6SubnetQueryResultOutput) ToGetIp6SubnetQueryResultOutput() GetIp6SubnetQueryResultOutput {
	return o
}

func (o GetIp6SubnetQueryResultOutput) ToGetIp6SubnetQueryResultOutputWithContext(ctx context.Context) GetIp6SubnetQueryResultOutput {
	return o
}

// The IP subnet address.
func (o GetIp6SubnetQueryResultOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) string { return v.Address }).(pulumi.StringOutput)
}

// The class associated to the IPv6 subnet.
func (o GetIp6SubnetQueryResultOutput) Class() pulumi.StringOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) string { return v.Class }).(pulumi.StringOutput)
}

// The class parameters associated to IPv6 subnet.
func (o GetIp6SubnetQueryResultOutput) ClassParameters() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) map[string]string { return v.ClassParameters }).(pulumi.StringMapOutput)
}

// The  IPv6 subnet's computed gateway.
func (o GetIp6SubnetQueryResultOutput) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) string { return v.Gateway }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetIp6SubnetQueryResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the IPv6 subnet.
func (o GetIp6SubnetQueryResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) string { return v.Name }).(pulumi.StringOutput)
}

// The query used to find the first matching subnet.
func (o GetIp6SubnetQueryResultOutput) Orderby() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) *string { return v.Orderby }).(pulumi.StringPtrOutput)
}

// The IPv6 subnet prefix.
func (o GetIp6SubnetQueryResultOutput) Prefix() pulumi.StringOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) string { return v.Prefix }).(pulumi.StringOutput)
}

// The IPv6 subnet's prefix length (ex: 64 for a '/64').
func (o GetIp6SubnetQueryResultOutput) PrefixSize() pulumi.IntOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) int { return v.PrefixSize }).(pulumi.IntOutput)
}

// The query used to find the first matching subnet.
func (o GetIp6SubnetQueryResultOutput) Query() pulumi.StringOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) string { return v.Query }).(pulumi.StringOutput)
}

// The space associated to the IPv6 subnet.
func (o GetIp6SubnetQueryResultOutput) Space() pulumi.StringOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) string { return v.Space }).(pulumi.StringOutput)
}

// The tags to be used to find the first matching subnet in the query.
func (o GetIp6SubnetQueryResultOutput) Tags() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) *string { return v.Tags }).(pulumi.StringPtrOutput)
}

// The terminal property of the IPv6 subnet.
func (o GetIp6SubnetQueryResultOutput) Terminal() pulumi.BoolOutput {
	return o.ApplyT(func(v GetIp6SubnetQueryResult) bool { return v.Terminal }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIp6SubnetQueryResultOutput{})
}
