// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package solidserver

import (
	"context"
	"reflect"

	"github.com/AthenaWolfe/pulumi-solidserver/sdk/go/solidserver/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// IPv6 subnet data-source allows to retrieve information about reserved IPv6 subnets, including meta-data.
// IPv6 Subnet are key to organize the IP space, they can be blocks or subnets. Blocks reflect assigned IP
// ranges (RFC1918 or public prefixes). Subnets reflect the internal sub-division of your network.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/AthenaWolfe/pulumi-solidserver/sdk/go/solidserver"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := solidserver.LookupIp6Subnet(ctx, &solidserver.LookupIp6SubnetArgs{
//				Name:  solidserver_ip6_subnet.MyFirstIP6Subnet.Name,
//				Space: solidserver_ip6_subnet.MyFirstIP6Subnet.Space,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupIp6Subnet(ctx *pulumi.Context, args *LookupIp6SubnetArgs, opts ...pulumi.InvokeOption) (*LookupIp6SubnetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupIp6SubnetResult
	err := ctx.Invoke("solidserver:index/getIp6Subnet:getIp6Subnet", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIp6Subnet.
type LookupIp6SubnetArgs struct {
	// The name of the IPv6 subnet.
	Name string `pulumi:"name"`
	// The space associated to the IPv6 subnet.
	Space string `pulumi:"space"`
}

// A collection of values returned by getIp6Subnet.
type LookupIp6SubnetResult struct {
	// The IP subnet address.
	Address string `pulumi:"address"`
	// The class associated to the IPv6 subnet.
	Class string `pulumi:"class"`
	// The class parameters associated to IPv6 subnet.
	ClassParameters map[string]string `pulumi:"classParameters"`
	// The  IPv6 subnet's computed gateway.
	Gateway string `pulumi:"gateway"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The name of the IPv6 subnet.
	Name string `pulumi:"name"`
	// The IPv6 subnet prefix.
	Prefix string `pulumi:"prefix"`
	// The IPv6 subnet's prefix length (ex: 64 for a '/64').
	PrefixSize int `pulumi:"prefixSize"`
	// The space associated to the IPv6 subnet.
	Space string `pulumi:"space"`
	// The terminal property of the IPv6 subnet.
	Terminal bool `pulumi:"terminal"`
	// The optional vlan ID associated with the subnet.
	VlanId int `pulumi:"vlanId"`
}

func LookupIp6SubnetOutput(ctx *pulumi.Context, args LookupIp6SubnetOutputArgs, opts ...pulumi.InvokeOption) LookupIp6SubnetResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupIp6SubnetResult, error) {
			args := v.(LookupIp6SubnetArgs)
			r, err := LookupIp6Subnet(ctx, &args, opts...)
			var s LookupIp6SubnetResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupIp6SubnetResultOutput)
}

// A collection of arguments for invoking getIp6Subnet.
type LookupIp6SubnetOutputArgs struct {
	// The name of the IPv6 subnet.
	Name pulumi.StringInput `pulumi:"name"`
	// The space associated to the IPv6 subnet.
	Space pulumi.StringInput `pulumi:"space"`
}

func (LookupIp6SubnetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIp6SubnetArgs)(nil)).Elem()
}

// A collection of values returned by getIp6Subnet.
type LookupIp6SubnetResultOutput struct{ *pulumi.OutputState }

func (LookupIp6SubnetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIp6SubnetResult)(nil)).Elem()
}

func (o LookupIp6SubnetResultOutput) ToLookupIp6SubnetResultOutput() LookupIp6SubnetResultOutput {
	return o
}

func (o LookupIp6SubnetResultOutput) ToLookupIp6SubnetResultOutputWithContext(ctx context.Context) LookupIp6SubnetResultOutput {
	return o
}

// The IP subnet address.
func (o LookupIp6SubnetResultOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) string { return v.Address }).(pulumi.StringOutput)
}

// The class associated to the IPv6 subnet.
func (o LookupIp6SubnetResultOutput) Class() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) string { return v.Class }).(pulumi.StringOutput)
}

// The class parameters associated to IPv6 subnet.
func (o LookupIp6SubnetResultOutput) ClassParameters() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) map[string]string { return v.ClassParameters }).(pulumi.StringMapOutput)
}

// The  IPv6 subnet's computed gateway.
func (o LookupIp6SubnetResultOutput) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) string { return v.Gateway }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupIp6SubnetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the IPv6 subnet.
func (o LookupIp6SubnetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) string { return v.Name }).(pulumi.StringOutput)
}

// The IPv6 subnet prefix.
func (o LookupIp6SubnetResultOutput) Prefix() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) string { return v.Prefix }).(pulumi.StringOutput)
}

// The IPv6 subnet's prefix length (ex: 64 for a '/64').
func (o LookupIp6SubnetResultOutput) PrefixSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) int { return v.PrefixSize }).(pulumi.IntOutput)
}

// The space associated to the IPv6 subnet.
func (o LookupIp6SubnetResultOutput) Space() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) string { return v.Space }).(pulumi.StringOutput)
}

// The terminal property of the IPv6 subnet.
func (o LookupIp6SubnetResultOutput) Terminal() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) bool { return v.Terminal }).(pulumi.BoolOutput)
}

// The optional vlan ID associated with the subnet.
func (o LookupIp6SubnetResultOutput) VlanId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIp6SubnetResult) int { return v.VlanId }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIp6SubnetResultOutput{})
}
