// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package solidserver

import (
	"context"
	"reflect"

	"github.com/AthenaWolfe/pulumi-solidserver/sdk/go/solidserver/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// VLAN data-source allows to retrieve information about vlans, including meta-data.
func LookupVlan(ctx *pulumi.Context, args *LookupVlanArgs, opts ...pulumi.InvokeOption) (*LookupVlanResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVlanResult
	err := ctx.Invoke("solidserver:index/getVlan:getVlan", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVlan.
type LookupVlanArgs struct {
	// The name of the vlan.
	Name string `pulumi:"name"`
	// The name of the vlan Domain.
	VlanDomain string `pulumi:"vlanDomain"`
	// The name of the vlan Range.
	VlanRange *string `pulumi:"vlanRange"`
}

// A collection of values returned by getVlan.
type LookupVlanResult struct {
	// The class associated to the vlan.
	Class string `pulumi:"class"`
	// The class parameters associated to vlan.
	ClassParameters map[string]interface{} `pulumi:"classParameters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The name of the vlan.
	Name string `pulumi:"name"`
	// The name of the vlan Domain.
	VlanDomain string `pulumi:"vlanDomain"`
	// The vlan ID.
	VlanId int `pulumi:"vlanId"`
	// The name of the vlan Range.
	VlanRange *string `pulumi:"vlanRange"`
}

func LookupVlanOutput(ctx *pulumi.Context, args LookupVlanOutputArgs, opts ...pulumi.InvokeOption) LookupVlanResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupVlanResult, error) {
			args := v.(LookupVlanArgs)
			r, err := LookupVlan(ctx, &args, opts...)
			var s LookupVlanResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupVlanResultOutput)
}

// A collection of arguments for invoking getVlan.
type LookupVlanOutputArgs struct {
	// The name of the vlan.
	Name pulumi.StringInput `pulumi:"name"`
	// The name of the vlan Domain.
	VlanDomain pulumi.StringInput `pulumi:"vlanDomain"`
	// The name of the vlan Range.
	VlanRange pulumi.StringPtrInput `pulumi:"vlanRange"`
}

func (LookupVlanOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVlanArgs)(nil)).Elem()
}

// A collection of values returned by getVlan.
type LookupVlanResultOutput struct{ *pulumi.OutputState }

func (LookupVlanResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVlanResult)(nil)).Elem()
}

func (o LookupVlanResultOutput) ToLookupVlanResultOutput() LookupVlanResultOutput {
	return o
}

func (o LookupVlanResultOutput) ToLookupVlanResultOutputWithContext(ctx context.Context) LookupVlanResultOutput {
	return o
}

// The class associated to the vlan.
func (o LookupVlanResultOutput) Class() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.Class }).(pulumi.StringOutput)
}

// The class parameters associated to vlan.
func (o LookupVlanResultOutput) ClassParameters() pulumi.MapOutput {
	return o.ApplyT(func(v LookupVlanResult) map[string]interface{} { return v.ClassParameters }).(pulumi.MapOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupVlanResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the vlan.
func (o LookupVlanResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.Name }).(pulumi.StringOutput)
}

// The name of the vlan Domain.
func (o LookupVlanResultOutput) VlanDomain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanResult) string { return v.VlanDomain }).(pulumi.StringOutput)
}

// The vlan ID.
func (o LookupVlanResultOutput) VlanId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVlanResult) int { return v.VlanId }).(pulumi.IntOutput)
}

// The name of the vlan Range.
func (o LookupVlanResultOutput) VlanRange() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVlanResult) *string { return v.VlanRange }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVlanResultOutput{})
}
