// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package solidserver

import (
	"context"
	"reflect"

	"github.com/AthenaWolfe/pulumi-solidserver/sdk/go/solidserver/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// VLAN range data-source allows to retrieve information about VLAN ranges, including meta-data.
func LookupVlanRange(ctx *pulumi.Context, args *LookupVlanRangeArgs, opts ...pulumi.InvokeOption) (*LookupVlanRangeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVlanRangeResult
	err := ctx.Invoke("solidserver:index/getVlanRange:getVlanRange", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVlanRange.
type LookupVlanRangeArgs struct {
	// The name of the VLAN Range.
	Name string `pulumi:"name"`
	// The name of the vlan Domain.
	VlanDomain string `pulumi:"vlanDomain"`
}

// A collection of values returned by getVlanRange.
type LookupVlanRangeResult struct {
	// The class associated to the VLAN Range.
	Class string `pulumi:"class"`
	// The class parameters associated to VLAN Range.
	ClassParameters map[string]interface{} `pulumi:"classParameters"`
	// The vlan range's higher vlan ID.
	End int `pulumi:"end"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The name of the VLAN Range.
	Name string `pulumi:"name"`
	// The vlan range's lower vlan ID.
	Start int `pulumi:"start"`
	// The name of the vlan Domain.
	VlanDomain string `pulumi:"vlanDomain"`
}

func LookupVlanRangeOutput(ctx *pulumi.Context, args LookupVlanRangeOutputArgs, opts ...pulumi.InvokeOption) LookupVlanRangeResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupVlanRangeResult, error) {
			args := v.(LookupVlanRangeArgs)
			r, err := LookupVlanRange(ctx, &args, opts...)
			var s LookupVlanRangeResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupVlanRangeResultOutput)
}

// A collection of arguments for invoking getVlanRange.
type LookupVlanRangeOutputArgs struct {
	// The name of the VLAN Range.
	Name pulumi.StringInput `pulumi:"name"`
	// The name of the vlan Domain.
	VlanDomain pulumi.StringInput `pulumi:"vlanDomain"`
}

func (LookupVlanRangeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVlanRangeArgs)(nil)).Elem()
}

// A collection of values returned by getVlanRange.
type LookupVlanRangeResultOutput struct{ *pulumi.OutputState }

func (LookupVlanRangeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVlanRangeResult)(nil)).Elem()
}

func (o LookupVlanRangeResultOutput) ToLookupVlanRangeResultOutput() LookupVlanRangeResultOutput {
	return o
}

func (o LookupVlanRangeResultOutput) ToLookupVlanRangeResultOutputWithContext(ctx context.Context) LookupVlanRangeResultOutput {
	return o
}

// The class associated to the VLAN Range.
func (o LookupVlanRangeResultOutput) Class() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanRangeResult) string { return v.Class }).(pulumi.StringOutput)
}

// The class parameters associated to VLAN Range.
func (o LookupVlanRangeResultOutput) ClassParameters() pulumi.MapOutput {
	return o.ApplyT(func(v LookupVlanRangeResult) map[string]interface{} { return v.ClassParameters }).(pulumi.MapOutput)
}

// The vlan range's higher vlan ID.
func (o LookupVlanRangeResultOutput) End() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVlanRangeResult) int { return v.End }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupVlanRangeResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanRangeResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the VLAN Range.
func (o LookupVlanRangeResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanRangeResult) string { return v.Name }).(pulumi.StringOutput)
}

// The vlan range's lower vlan ID.
func (o LookupVlanRangeResultOutput) Start() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVlanRangeResult) int { return v.Start }).(pulumi.IntOutput)
}

// The name of the vlan Domain.
func (o LookupVlanRangeResultOutput) VlanDomain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVlanRangeResult) string { return v.VlanDomain }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVlanRangeResultOutput{})
}
