// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("solidserver");

/**
 * PEM formatted file with additional certificates to trust for TLS connection
 */
export declare const additionalTrustCertsFile: string | undefined;
Object.defineProperty(exports, "additionalTrustCertsFile", {
    get() {
        return __config.get("additionalTrustCertsFile");
    },
    enumerable: true,
});

/**
 * SOLIDServer Hostname or IP address
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});

/**
 * SOLIDServer API user's password
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * SOLIDServer Version in case API user does not have admin permissions
 */
export declare const solidserverversion: string | undefined;
Object.defineProperty(exports, "solidserverversion", {
    get() {
        return __config.get("solidserverversion");
    },
    enumerable: true,
});

/**
 * Enable/Disable ssl verify (Default : enabled)
 */
export declare const sslverify: boolean | undefined;
Object.defineProperty(exports, "sslverify", {
    get() {
        return __config.getObject<boolean>("sslverify");
    },
    enumerable: true,
});

/**
 * SOLIDServer API user's ID
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

