// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Custom DB Data data-source allows to retrieve custom database entries stored within SOLIDserver.
 * This custom database entries can be leveraged within object classes and wizards in order to store custom meta-data.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as solidserver from "@pulumi/solidserver";
 *
 * const myCustomData = solidserver.getCdbData({
 *     customDb: "myFirstCustomDB",
 *     value1: "FR",
 * });
 * ```
 */
export function getCdbData(args: GetCdbDataArgs, opts?: pulumi.InvokeOptions): Promise<GetCdbDataResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("solidserver:index/getCdbData:getCdbData", {
        "customDb": args.customDb,
        "value1": args.value1,
    }, opts);
}

/**
 * A collection of arguments for invoking getCdbData.
 */
export interface GetCdbDataArgs {
    /**
     * The name of the custom DB.
     */
    customDb: string;
    /**
     * The name of the value 1
     */
    value1: string;
}

/**
 * A collection of values returned by getCdbData.
 */
export interface GetCdbDataResult {
    /**
     * The name of the custom DB.
     */
    readonly customDb: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the value 1
     */
    readonly value1: string;
    /**
     * The name of the value 10
     */
    readonly value10: string;
    /**
     * The name of the value 2
     */
    readonly value2: string;
    /**
     * The name of the value 3
     */
    readonly value3: string;
    /**
     * The name of the value 4
     */
    readonly value4: string;
    /**
     * The name of the value 5
     */
    readonly value5: string;
    /**
     * The name of the value 6
     */
    readonly value6: string;
    /**
     * The name of the value 7
     */
    readonly value7: string;
    /**
     * The name of the value 8
     */
    readonly value8: string;
    /**
     * The name of the value 9
     */
    readonly value9: string;
}
/**
 * Custom DB Data data-source allows to retrieve custom database entries stored within SOLIDserver.
 * This custom database entries can be leveraged within object classes and wizards in order to store custom meta-data.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as solidserver from "@pulumi/solidserver";
 *
 * const myCustomData = solidserver.getCdbData({
 *     customDb: "myFirstCustomDB",
 *     value1: "FR",
 * });
 * ```
 */
export function getCdbDataOutput(args: GetCdbDataOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCdbDataResult> {
    return pulumi.output(args).apply((a: any) => getCdbData(a, opts))
}

/**
 * A collection of arguments for invoking getCdbData.
 */
export interface GetCdbDataOutputArgs {
    /**
     * The name of the custom DB.
     */
    customDb: pulumi.Input<string>;
    /**
     * The name of the value 1
     */
    value1: pulumi.Input<string>;
}
