// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * DNS server data-source allows to retrieve information about DNS servers.
 * Most of the time, they are just added to a SMART, but they can remain standalone.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as solidserver from "@pulumi/solidserver";
 *
 * const dnsServerData = solidserver.getDnsServer({
 *     name: "ns.local",
 * });
 * ```
 */
export function getDnsServer(args: GetDnsServerArgs, opts?: pulumi.InvokeOptions): Promise<GetDnsServerResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("solidserver:index/getDnsServer:getDnsServer", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDnsServer.
 */
export interface GetDnsServerArgs {
    /**
     * The name of the DNS server.
     */
    name: string;
}

/**
 * A collection of values returned by getDnsServer.
 */
export interface GetDnsServerResult {
    /**
     * IPv4 address of the DNS server.
     */
    readonly address: string;
    /**
     * A list of network prefixes allowed to query the DNS server (named ACL(s) are not supported using this provider).
     */
    readonly allowQueries: string[];
    /**
     * A list of network prefixes allowed to query the DNS server for recursion (named ACL(s) are not supported using this provider).
     */
    readonly allowRecursions: string[];
    /**
     * A list of network prefixes allowed to query the DNS server for zone transfert (named ACL(s) are not supported using this provider).
     */
    readonly allowTransfers: string[];
    /**
     * The class associated to the DNS server.
     */
    readonly class: string;
    /**
     * The class parameters associated to the DNS server.
     */
    readonly classParameters: {[key: string]: any};
    /**
     * Custom information about the DNS server.
     */
    readonly comment: string;
    /**
     * The forwarding mode of the DNS server (disabled if empty).
     */
    readonly forward: string;
    /**
     * The IP address list of the forwarder(s) configured on the DNS server.
     */
    readonly forwarders: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the DNS server.
     */
    readonly name: string;
    /**
     * The recursion status of the DNS server.
     */
    readonly recursion: boolean;
    /**
     * The type of DNS server (ipm (SOLIDserver DNS)|msdaemon (Microsoft DNS)|ans (Nominum)|aws (AWS Route-53)|other (Other DNS)).
     */
    readonly type: string;
    /**
     * DNS Engine Version.
     */
    readonly version: string;
}
/**
 * DNS server data-source allows to retrieve information about DNS servers.
 * Most of the time, they are just added to a SMART, but they can remain standalone.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as solidserver from "@pulumi/solidserver";
 *
 * const dnsServerData = solidserver.getDnsServer({
 *     name: "ns.local",
 * });
 * ```
 */
export function getDnsServerOutput(args: GetDnsServerOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDnsServerResult> {
    return pulumi.output(args).apply((a: any) => getDnsServer(a, opts))
}

/**
 * A collection of arguments for invoking getDnsServer.
 */
export interface GetDnsServerOutputArgs {
    /**
     * The name of the DNS server.
     */
    name: pulumi.Input<string>;
}
