// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * IP pool data-source allows to retrieve information about reserved IPv4 pools including meta-data.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as solidserver from "@pulumi/solidserver";
 *
 * const myFirstIPPoolData = solidserver.getIpPool({
 *     name: solidserver_ip_subnet.myFirstIPPool.name,
 *     subnet: solidserver_ip_subnet.myFirstIPPool.subnet,
 *     space: solidserver_ip_subnet.myFirstIPPool.space,
 * });
 * ```
 */
export function getIpPool(args: GetIpPoolArgs, opts?: pulumi.InvokeOptions): Promise<GetIpPoolResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("solidserver:index/getIpPool:getIpPool", {
        "name": args.name,
        "space": args.space,
        "subnet": args.subnet,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpPool.
 */
export interface GetIpPoolArgs {
    /**
     * The name of the IP pool.
     */
    name: string;
    /**
     * The space associated to the IP pool.
     */
    space: string;
    /**
     * The parent subnet of the IP pool.
     */
    subnet: string;
}

/**
 * A collection of values returned by getIpPool.
 */
export interface GetIpPoolResult {
    /**
     * The class associated to the IP pool.
     */
    readonly class: string;
    /**
     * The class parameters associated to the IP pool.
     */
    readonly classParameters: {[key: string]: any};
    /**
     * The last address of the IP pool.
     */
    readonly end: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the IP pool.
     */
    readonly name: string;
    /**
     * The prefix of the parent subnet of the IP pool.
     */
    readonly prefix: string;
    /**
     * The size prefix of the parent subnet of the IP pool.
     */
    readonly prefixSize: number;
    /**
     * The size of the IP pool.
     */
    readonly size: string;
    /**
     * The space associated to the IP pool.
     */
    readonly space: string;
    /**
     * The fisrt address of the IP pool.
     */
    readonly start: string;
    /**
     * The parent subnet of the IP pool.
     */
    readonly subnet: string;
}
/**
 * IP pool data-source allows to retrieve information about reserved IPv4 pools including meta-data.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as solidserver from "@pulumi/solidserver";
 *
 * const myFirstIPPoolData = solidserver.getIpPool({
 *     name: solidserver_ip_subnet.myFirstIPPool.name,
 *     subnet: solidserver_ip_subnet.myFirstIPPool.subnet,
 *     space: solidserver_ip_subnet.myFirstIPPool.space,
 * });
 * ```
 */
export function getIpPoolOutput(args: GetIpPoolOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIpPoolResult> {
    return pulumi.output(args).apply((a: any) => getIpPool(a, opts))
}

/**
 * A collection of arguments for invoking getIpPool.
 */
export interface GetIpPoolOutputArgs {
    /**
     * The name of the IP pool.
     */
    name: pulumi.Input<string>;
    /**
     * The space associated to the IP pool.
     */
    space: pulumi.Input<string>;
    /**
     * The parent subnet of the IP pool.
     */
    subnet: pulumi.Input<string>;
}
