// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * VLAN data-source allows to retrieve information about vlans, including meta-data.
 */
export function getVlan(args: GetVlanArgs, opts?: pulumi.InvokeOptions): Promise<GetVlanResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("solidserver:index/getVlan:getVlan", {
        "name": args.name,
        "vlanDomain": args.vlanDomain,
        "vlanRange": args.vlanRange,
    }, opts);
}

/**
 * A collection of arguments for invoking getVlan.
 */
export interface GetVlanArgs {
    /**
     * The name of the vlan.
     */
    name: string;
    /**
     * The name of the vlan Domain.
     */
    vlanDomain: string;
    /**
     * The name of the vlan Range.
     */
    vlanRange?: string;
}

/**
 * A collection of values returned by getVlan.
 */
export interface GetVlanResult {
    /**
     * The class associated to the vlan.
     */
    readonly class: string;
    /**
     * The class parameters associated to vlan.
     */
    readonly classParameters: {[key: string]: any};
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the vlan.
     */
    readonly name: string;
    /**
     * The name of the vlan Domain.
     */
    readonly vlanDomain: string;
    /**
     * The vlan ID.
     */
    readonly vlanId: number;
    /**
     * The name of the vlan Range.
     */
    readonly vlanRange?: string;
}
/**
 * VLAN data-source allows to retrieve information about vlans, including meta-data.
 */
export function getVlanOutput(args: GetVlanOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVlanResult> {
    return pulumi.output(args).apply((a: any) => getVlan(a, opts))
}

/**
 * A collection of arguments for invoking getVlan.
 */
export interface GetVlanOutputArgs {
    /**
     * The name of the vlan.
     */
    name: pulumi.Input<string>;
    /**
     * The name of the vlan Domain.
     */
    vlanDomain: pulumi.Input<string>;
    /**
     * The name of the vlan Range.
     */
    vlanRange?: pulumi.Input<string>;
}
