// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * VLAN range data-source allows to retrieve information about VLAN ranges, including meta-data.
 */
export function getVlanRange(args: GetVlanRangeArgs, opts?: pulumi.InvokeOptions): Promise<GetVlanRangeResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("solidserver:index/getVlanRange:getVlanRange", {
        "name": args.name,
        "vlanDomain": args.vlanDomain,
    }, opts);
}

/**
 * A collection of arguments for invoking getVlanRange.
 */
export interface GetVlanRangeArgs {
    /**
     * The name of the VLAN Range.
     */
    name: string;
    /**
     * The name of the vlan Domain.
     */
    vlanDomain: string;
}

/**
 * A collection of values returned by getVlanRange.
 */
export interface GetVlanRangeResult {
    /**
     * The class associated to the VLAN Range.
     */
    readonly class: string;
    /**
     * The class parameters associated to VLAN Range.
     */
    readonly classParameters: {[key: string]: any};
    /**
     * The vlan range's higher vlan ID.
     */
    readonly end: number;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the VLAN Range.
     */
    readonly name: string;
    /**
     * The vlan range's lower vlan ID.
     */
    readonly start: number;
    /**
     * The name of the vlan Domain.
     */
    readonly vlanDomain: string;
}
/**
 * VLAN range data-source allows to retrieve information about VLAN ranges, including meta-data.
 */
export function getVlanRangeOutput(args: GetVlanRangeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVlanRangeResult> {
    return pulumi.output(args).apply((a: any) => getVlanRange(a, opts))
}

/**
 * A collection of arguments for invoking getVlanRange.
 */
export interface GetVlanRangeOutputArgs {
    /**
     * The name of the VLAN Range.
     */
    name: pulumi.Input<string>;
    /**
     * The name of the vlan Domain.
     */
    vlanDomain: pulumi.Input<string>;
}
