// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * VLAN domain data-source allows to retrieve information about VLAN Domains, including meta-data.
 */
export function getVlanDomain(args: GetVlanDomainArgs, opts?: pulumi.InvokeOptions): Promise<GetVlanDomainResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("solidserver:index/getVlanDomain:getVlanDomain", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getVlanDomain.
 */
export interface GetVlanDomainArgs {
    /**
     * The name of the VLAN Domain.
     */
    name: string;
}

/**
 * A collection of values returned by getVlanDomain.
 */
export interface GetVlanDomainResult {
    /**
     * The class associated to the VLAN Domain.
     */
    readonly class: string;
    /**
     * The class parameters associated to VLAN Domain.
     */
    readonly classParameters: {[key: string]: any};
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the VLAN Domain.
     */
    readonly name: string;
    /**
     * Specify if the VLAN Domain is a VXLAN Domain.
     */
    readonly vxlan: boolean;
}
/**
 * VLAN domain data-source allows to retrieve information about VLAN Domains, including meta-data.
 */
export function getVlanDomainOutput(args: GetVlanDomainOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVlanDomainResult> {
    return pulumi.output(args).apply((a: any) => getVlanDomain(a, opts))
}

/**
 * A collection of arguments for invoking getVlanDomain.
 */
export interface GetVlanDomainOutputArgs {
    /**
     * The name of the VLAN Domain.
     */
    name: pulumi.Input<string>;
}
