// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * IP address resource allows to create and manage reserved addresses for specific devices, apps or users.
 * More importantly it allows to store useful meta-data for both tracking and automation purposes.
 */
export class IpAddress extends pulumi.CustomResource {
    /**
     * Get an existing IpAddress resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpAddressState, opts?: pulumi.CustomResourceOptions): IpAddress {
        return new IpAddress(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'solidserver:index/ipAddress:IpAddress';

    /**
     * Returns true if the given object is an instance of IpAddress.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpAddress {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpAddress.__pulumiType;
    }

    /**
     * The provisionned IP address.
     */
    public /*out*/ readonly address!: pulumi.Output<string>;
    /**
     * The class associated to the IP address.
     */
    public readonly class!: pulumi.Output<string | undefined>;
    /**
     * The class parameters associated to the IP address.
     */
    public readonly classParameters!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Device Name to associate with the IP address (Require a 'Device Manager' license).
     */
    public readonly device!: pulumi.Output<string | undefined>;
    /**
     * The MAC Address of the IP address to create.
     */
    public readonly mac!: pulumi.Output<string | undefined>;
    /**
     * The short name or FQDN of the IP address to create.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The name of the pool into which creating the IP address.
     */
    public readonly pool!: pulumi.Output<string | undefined>;
    /**
     * The optionally requested IP address.
     */
    public readonly requestIp!: pulumi.Output<string | undefined>;
    /**
     * The name of the space into which creating the IP address.
     */
    public readonly space!: pulumi.Output<string>;
    /**
     * The name of the subnet into which creating the IP address.
     */
    public readonly subnet!: pulumi.Output<string>;

    /**
     * Create a IpAddress resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IpAddressArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpAddressArgs | IpAddressState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpAddressState | undefined;
            resourceInputs["address"] = state ? state.address : undefined;
            resourceInputs["class"] = state ? state.class : undefined;
            resourceInputs["classParameters"] = state ? state.classParameters : undefined;
            resourceInputs["device"] = state ? state.device : undefined;
            resourceInputs["mac"] = state ? state.mac : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["pool"] = state ? state.pool : undefined;
            resourceInputs["requestIp"] = state ? state.requestIp : undefined;
            resourceInputs["space"] = state ? state.space : undefined;
            resourceInputs["subnet"] = state ? state.subnet : undefined;
        } else {
            const args = argsOrState as IpAddressArgs | undefined;
            if ((!args || args.space === undefined) && !opts.urn) {
                throw new Error("Missing required property 'space'");
            }
            if ((!args || args.subnet === undefined) && !opts.urn) {
                throw new Error("Missing required property 'subnet'");
            }
            resourceInputs["class"] = args ? args.class : undefined;
            resourceInputs["classParameters"] = args ? args.classParameters : undefined;
            resourceInputs["device"] = args ? args.device : undefined;
            resourceInputs["mac"] = args ? args.mac : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["pool"] = args ? args.pool : undefined;
            resourceInputs["requestIp"] = args ? args.requestIp : undefined;
            resourceInputs["space"] = args ? args.space : undefined;
            resourceInputs["subnet"] = args ? args.subnet : undefined;
            resourceInputs["address"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpAddress.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IpAddress resources.
 */
export interface IpAddressState {
    /**
     * The provisionned IP address.
     */
    address?: pulumi.Input<string>;
    /**
     * The class associated to the IP address.
     */
    class?: pulumi.Input<string>;
    /**
     * The class parameters associated to the IP address.
     */
    classParameters?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Device Name to associate with the IP address (Require a 'Device Manager' license).
     */
    device?: pulumi.Input<string>;
    /**
     * The MAC Address of the IP address to create.
     */
    mac?: pulumi.Input<string>;
    /**
     * The short name or FQDN of the IP address to create.
     */
    name?: pulumi.Input<string>;
    /**
     * The name of the pool into which creating the IP address.
     */
    pool?: pulumi.Input<string>;
    /**
     * The optionally requested IP address.
     */
    requestIp?: pulumi.Input<string>;
    /**
     * The name of the space into which creating the IP address.
     */
    space?: pulumi.Input<string>;
    /**
     * The name of the subnet into which creating the IP address.
     */
    subnet?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IpAddress resource.
 */
export interface IpAddressArgs {
    /**
     * The class associated to the IP address.
     */
    class?: pulumi.Input<string>;
    /**
     * The class parameters associated to the IP address.
     */
    classParameters?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Device Name to associate with the IP address (Require a 'Device Manager' license).
     */
    device?: pulumi.Input<string>;
    /**
     * The MAC Address of the IP address to create.
     */
    mac?: pulumi.Input<string>;
    /**
     * The short name or FQDN of the IP address to create.
     */
    name?: pulumi.Input<string>;
    /**
     * The name of the pool into which creating the IP address.
     */
    pool?: pulumi.Input<string>;
    /**
     * The optionally requested IP address.
     */
    requestIp?: pulumi.Input<string>;
    /**
     * The name of the space into which creating the IP address.
     */
    space: pulumi.Input<string>;
    /**
     * The name of the subnet into which creating the IP address.
     */
    subnet: pulumi.Input<string>;
}
