// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * User resource allows to creat and manage local SOLIDserver users who
 * can connect through Web GUI and use API(s).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as solidserver from "@pulumi/solidserver";
 *
 * const myFirstUser = new solidserver.User("myFirstUser", {
 *     description: "My Very First User Resource",
 *     email: "j.smith@efficientip.com",
 *     firstName: "John",
 *     groups: [solidserver_usergroup.grp_admin.name],
 *     lastName: "Smith",
 *     login: "jsmith",
 *     password: "a_very_c0mpl3x_P@ssw0rd",
 * });
 * ```
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'solidserver:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * The class parameters associated to the user.
     */
    public readonly classParameters!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The description of the user
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The email address of the user
     */
    public readonly email!: pulumi.Output<string | undefined>;
    /**
     * The first name of the user
     */
    public readonly firstName!: pulumi.Output<string | undefined>;
    /**
     * The group id set for this user
     */
    public readonly groups!: pulumi.Output<string[]>;
    /**
     * The last name of the user
     */
    public readonly lastName!: pulumi.Output<string | undefined>;
    /**
     * The login of the user
     */
    public readonly login!: pulumi.Output<string>;
    /**
     * The password of the user
     */
    public readonly password!: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["classParameters"] = state ? state.classParameters : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["email"] = state ? state.email : undefined;
            resourceInputs["firstName"] = state ? state.firstName : undefined;
            resourceInputs["groups"] = state ? state.groups : undefined;
            resourceInputs["lastName"] = state ? state.lastName : undefined;
            resourceInputs["login"] = state ? state.login : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if ((!args || args.groups === undefined) && !opts.urn) {
                throw new Error("Missing required property 'groups'");
            }
            if ((!args || args.login === undefined) && !opts.urn) {
                throw new Error("Missing required property 'login'");
            }
            if ((!args || args.password === undefined) && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            resourceInputs["classParameters"] = args ? args.classParameters : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["email"] = args ? args.email : undefined;
            resourceInputs["firstName"] = args ? args.firstName : undefined;
            resourceInputs["groups"] = args ? args.groups : undefined;
            resourceInputs["lastName"] = args ? args.lastName : undefined;
            resourceInputs["login"] = args ? args.login : undefined;
            resourceInputs["password"] = args ? args.password : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * The class parameters associated to the user.
     */
    classParameters?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The description of the user
     */
    description?: pulumi.Input<string>;
    /**
     * The email address of the user
     */
    email?: pulumi.Input<string>;
    /**
     * The first name of the user
     */
    firstName?: pulumi.Input<string>;
    /**
     * The group id set for this user
     */
    groups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The last name of the user
     */
    lastName?: pulumi.Input<string>;
    /**
     * The login of the user
     */
    login?: pulumi.Input<string>;
    /**
     * The password of the user
     */
    password?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * The class parameters associated to the user.
     */
    classParameters?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The description of the user
     */
    description?: pulumi.Input<string>;
    /**
     * The email address of the user
     */
    email?: pulumi.Input<string>;
    /**
     * The first name of the user
     */
    firstName?: pulumi.Input<string>;
    /**
     * The group id set for this user
     */
    groups: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The last name of the user
     */
    lastName?: pulumi.Input<string>;
    /**
     * The login of the user
     */
    login: pulumi.Input<string>;
    /**
     * The password of the user
     */
    password: pulumi.Input<string>;
}
